CREATE TABLE "groups" (
    id      int         GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1),
    title   text        NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE "member" (
    id              int         GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1),
    read_page_count smallint    NOT NULL,
    name            text        NOT NULL,
    group_id        int         NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT "mg_ref" FOREIGN KEY (group_id) REFERENCES "groups" (id)
);

CREATE TABLE "member_page" (
    period_id           int         NOT NULL,
    member_id           int         NOT NULL,
    first_page          smallint    NOT NULL,
    page_count          smallint    NOT NULL,
    date_timestamp      timestamptz NOT NULL,
    status              smallint    NOT NULL,

    CONSTRAINT "mpm_ref" FOREIGN KEY (member_id) REFERENCES "member" (id),
    CONSTRAINT "mpp_ref" FOREIGN KEY (period_id) REFERENCES "period" (id)
);

CREATE TABLE "period" (
    id          int         NOT NULL,
    group_id    int         NOT NULL,
    created_at  timestamptz NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT "pg_ref" FOREIGN KEY (group_id) REFERENCES "groups" (id)
);